version: "3.3"

services:
  devsetgoTest:
    image: mikeryan56/dsg:beta-2024-09-02-3
    env_file:
      - .env
    restart: always
    ports:
      - "5000"
    networks:
      - web
      - postgresql_db_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dsg-web-test.rule=Host(`test.devsetgo.com`)"
      - "traefik.http.routers.dsg-web-test.entrypoints=web"
      - "traefik.http.routers.dsg-web-test.middlewares=redirect@file"
      - "traefik.http.routers.dsg-test-secured.rule=Host(`test.devsetgo.com`)"
      - "traefik.http.routers.dsg-test-secured.entrypoints=web-secured"
      - "traefik.http.routers.dsg-test-secured.tls.certresolver=mytlschallenge"
    volumes:
      - log-volume:/app/log
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 30s
      restart_policy:
        condition: on-failure

networks:
  web:
    external: true
  postgresql_db_network:
    external: true

volumes:
  devsetgoTest:
    external: false
  log-volume:
    driver: local
