version: "3.3"

services:
  # sevenofi site service
  devsetgo:
      image: mikeryan56/dsg:beta-24-04-27
      container_name: "devsetgoTest"
      restart: always
      ports:
      - "5000"
      volumes:
      - .:/code
      networks:
          - web
          - backend
      labels:
          # - "traefik.http.middlewares.dsg-test-https.redirectscheme.scheme=https"
          #### Labels define the behavior and rules of the traefik proxy for this container ####
          - "traefik.enable=true" # <== Enable traefik to proxy this container
          - "traefik.http.routers.dsg-web-test.rule=Host(`test.devsetgo.com`)" # <== Your Domain Name goes here for the http rule
          - "traefik.http.routers.dsg-web-test.entrypoints=web" # <== Defining the entrypoint for http, **ref: line 30
          - "traefik.http.routers.dsg-web-test.middlewares=redirect@file" # <== This is a middleware to redirect to https
          - "traefik.http.routers.dsg-test-secured.rule=Host(`test.devsetgo.com`)" # <== Your Domain Name for the https rule 
          - "traefik.http.routers.dsg-test-secured.entrypoints=web-secured" # <== Defining entrypoint for https, **ref: line 31
          - "traefik.http.routers.dsg-test-secured.tls.certresolver=mytlschallenge" # <== Defining certsresolvers for https
    
networks:
  web:
    external: true
  backend:
    external: true
  db_network: