version: "3.3"

services:
  devsetgo:
    image: mikeryan56/dsg:beta-24-06-01-2215
    env_file:
      - .env
    container_name: "devsetgoTest"
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - devsetgo:/app
    networks:
      - web
      - backend
      - postgres_db_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dsg-web-test.rule=Host(`test.devsetgo.com`)"
      - "traefik.http.routers.dsg-web-test.entrypoints=web"
      - "traefik.http.routers.dsg-web-test.middlewares=redirect@file"
      - "traefik.http.routers.dsg-test-secured.rule=Host(`test.devsetgo.com`)"
      - "traefik.http.routers.dsg-test-secured.entrypoints=web-secured"
      - "traefik.http.routers.dsg-test-secured.tls.certresolver=mytlschallenge"

networks:
  web:
    external: true
  backend:
    external: true
  postgres_db_network:
    external: true

volumes:
  devsetgo:
    external: false