version: "3.3"

services:
  devsetgo:
      image: mikeryan56/dsg:beta-24-04-27
      container_name: "devsetgoTest"
      restart: always
      ports:
      - "5000"
      volumes:
      - .:/code
      - ./data:/data
      - ./static/image/posts:/static/image/posts
      - ./sqlite_db:/sqlite_db
      networks:
          - web
          - backend
      labels:
          - "traefik.enable=true"
          - "traefik.http.routers.dsg-web-test.rule=Host(`test.devsetgo.com`)"
          - "traefik.http.routers.dsg-web-test.entrypoints=web"
          - "traefik.http.routers.dsg-web-test.middlewares=redirect@file"
          - "traefik.http.routers.dsg-test-secured.rule=Host(`test.devsetgo.com`)"
          - "traefik.http.routers.dsg-test-secured.entrypoints=web-secured"
          - "traefik.http.routers.dsg-test-secured.tls.certresolver=mytlschallenge"

networks:
  web:
    external: true
  backend:
    external: true
  db_network: