version: "3.3"

services:
  devsetgoTest:
    image: mikeryan56/dsg:beta-2024-09-13-002
    env_file:
      - .env
    restart: always
    ports:
      - "5000"
    networks:
      - web
      - postrgresql_db_network
    labels:
      - "traefik.http.middlewares.dsg-https.redirectscheme.scheme=https"
      #### Labels define the behavior and rules of the traefik proxy for this container ####
      - "traefik.enable=true" # <== Enable traefik to proxy this container
      - "traefik.http.routers.dsg-test-web.rule=Host(`test.devsetgo.com`)" # <== Your Domain Name goes here for the http rule
      - "traefik.http.routers.dsg-test-web.entrypoints=web" # <== Defining the entrypoint for http, **ref: line 30
      - "traefik.http.routers.dsg-test-web.middlewares=redirect@file" # <== This is a middleware to redirect to https
      - "traefik.http.routers.dsg-test-secured.rule=Host(`test.devsetgo.com`)" # <== Your Domain Name for the https rule 
      - "traefik.http.routers.dsg-test-secured.entrypoints=web-secured" # <== Defining entrypoint for https, **ref: line 31
      - "traefik.http.routers.dsg-test-secured.tls.certresolver=mytlschallenge" # <== Defining certsresolvers for https

    volumes:
      - log-volume:/app/log
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 90s
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD-SHELL", "curl -f https://devsetgo.com/api/health/status || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 3
networks:
  web:
    external: true
  postrgresql_db_network:
    external: true

volumes:
  devsetgoTest:
    external: false
  log-volume:
    driver: local
