FROM python:3.11
RUN apt-get update && apt-get -y install gcc
EXPOSE 5000
COPY . /src
WORKDIR /src
# Evironment Variables
ENV USE_ENV='docker'
# Application information - Calendar Versioning
ENV APP_VERSION='23.5.28'
ENV DEBUG=False
#prd for production or 'dev' for development
ENV RELEASE_ENV='prd'
ENV WORKERS=2
ENV SQLALCHEMY_DATABASE_URI='sqlite:///sqlite_db/api.db'
# postgresql://user:pass@localhost:5432/my_db
# Loguru settings
ENV LOGURU_RETENTION='10 days'
ENV LOGURU_ROTATION='100 MB'
# Values NOTSET, DEBUG, INFO, WARNING, ERROR, CRITICAL
ENV LOGURU_LOGGING_LEVEL='INFO'
# Lax, Strict, None
ENV SAME_SITE="Strict"
#Bool True/False
ENV HTTPS_ONLY=True
#Github
ENV GITHUB_ID="devsetgo"
ENV GITHUB_TOKEN="<enter you key>"
ENV GITHUB_REPO_LIMIT=100
#install requirements
RUN pip3 install --upgrade pip setuptools wheel
RUN pip3 install -r requirements.txt
# CMD ["uvicorn", "main:app","--port","5000"]
CMD ["gunicorn",  "-c", "gunicorn_cfg.py", "main:app"]
