FROM python:3.8-slim-buster
RUN apt-get update && apt-get -y install gcc
MAINTAINER Mike Ryan "mikeryan56@gmail.com"
EXPOSE 5000
COPY . /src
WORKDIR /src
# Evironment Variables
ENV USE_ENV='docker'
# Application information
ENV APP_VERSION='1.0.0'
# Add Demo Data
ENV DEMO_DATA_CREATE=False
# how many loops of requests
ENV DEMO_DATA_LOOPS=0
#This should be false for production
ENV DEBUG=False
#prd for production or 'dev' for development
ENV RELEASE_ENV='dev'
ENV SQLALCHEMY_DATABASE_URI='sqlite:///sqlite_db/api.db'
# postgresql://user:pass@localhost:5432/my_db
# Loguru settings
ENV LOGURU_RETENTION='10 days'
ENV LOGURU_ROTATION='100 MB'
# Values NOTSET, DEBUG, INFO, WARNING, ERROR, CRITICAL
ENV LOGURU_LOGGING_LEVEL='INFO'
#install requirements
RUN pip3 install --upgrade pip setuptools wheel
RUN pip3 install -r requirements.txt
# CMD ["python3", "main.py"]
CMD ["gunicorn",  "-c", "gunicorn_cfg.py", "main:app"]
